### ISSUE TITLE
Transform icons

### ISSUE THREAD

**Issue by pgilfernandez** [friction2d/friction-icon-theme#14]
Screenshot:
![Screenshot from 2024-10-30 15-20-21](https://github.com/user-attachments/assets/255eb4f3-d9e4-432c-9db5-c6dd205a38e0)

_Originally posted by @rodlie in https://github.com/friction2d/friction-icon-theme/issues/11#issuecomment-2447342042_

I don't know what happened or what did you want to do but in 9adaee76bea41a9da68f8286b239f11dba188323 or in aa20117559e360bc38878496900e5b892983c28d but pointTransform got overwritten by a Blender icon (a pointer that I like a lot but I didn't see you using it).

Well, what I mean with this issue is to balance boxTransform and pointTransform so that they both follow the same design as they both "transform" but "different elements".
My proposals would be:

<img width="140" alt="pointers" src="https://github.com/user-attachments/assets/9976dfca-5907-4c4e-a75b-cadedfa13043">

I like the right one better (based on Blender icons) but you decide :-)

**Comment by rodlie** [comment]
Merged.
