### ISSUE TITLE
Icons in 'NoInterpolation' need a SVG source

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction-icon-theme#5]
We don't have any sources for these icons, replace with something similar.

**Comment by adambelis** [comment]
can you add screan shot wich are thies ?

**Comment by rodlie** [comment]
https://github.com/friction2d/friction-icon-theme/tree/main/noInterpolation

I'm on a Mac at the moment, but I did have a very old build:

<img width="65" alt="Skjermbilde 2024-05-31 kl  09 40 48" src="https://github.com/friction2d/friction-icon-theme/assets/34516798/384010ea-a56f-4be3-8373-818698a38a88">

<img width="290" alt="Skjermbilde 2024-05-31 kl  09 40 33" src="https://github.com/friction2d/friction-icon-theme/assets/34516798/56206ab6-c575-4a07-9ec3-752bcb2b149d">

Yeah, not that hard to replace, just never did :)

**Comment by adambelis** [comment]
so they should stay 10x10 ? or should i switch to 16x16

**Comment by rodlie** [comment]
10x10 is not a requirement, don't know why they are 10x10 in the first place :)

**Comment by rodlie** [comment]
Home and just tested the icons. We do need to make some size adjustments, else ok for the fill and stroke icons. The graph icon still need some work.

![friction-noInterpolation-new](https://github.com/friction2d/friction-icon-theme/assets/34516798/70613070-2729-43fe-919e-f491c09a9576)

We probably need a guideline for padding in the SVG's.

**Comment by rodlie** [comment]
Better:
![friction-graph-prop2](https://github.com/friction2d/friction-icon-theme/assets/34516798/083ca1e8-1efc-4945-a0b4-729f5b24c82c)

https://github.com/friction2d/friction-icon-theme/blob/main/hicolor/scalable/friction/graph_property_2.svg

But I still don't think it works with the colored background.

Regarding the icon size, I will make _2 versions of the SVGs that have identical padding/size as the old icons to avoid padding issues in 0.9.6. Will fix it properly for v1.

**Comment by adambelis** [comment]
hmm .. i think this is kind of hacky implantation for checkboxes on that graph .   that checkbox color is set 12x12 px wich is probably custom set for that old 10x10 format . but my 16x16 ixon seemts to be render with 18x18 px.
 But i agree that that  icons for grap seems to chunky for that small  row
 
 
 I am ok to make it to if to 10x10 pixels just  you need to know that is kind of sort of hacky  special case. since other icons seem to render 16x16px .
 
 
![image](https://github.com/friction2d/friction-icon-theme/assets/50795097/20b36efb-c818-4224-8cee-47eca1067b22)

**Comment by rodlie** [comment]
I'm not blocking 0.9.6 just because of icons ;) I will just add identical padding in the SVGs and call them _2. Will refactor this for v1.

**Comment by adambelis** [comment]
> But I still don't think it works with the colored background.

I agree i think they need a second black outline 

![image](https://github.com/friction2d/friction-icon-theme/assets/50795097/1c559bd4-0cf9-4baf-b2eb-f514fa843777)

**Comment by rodlie** [comment]
Yes, that would probably work.

**Comment by adambelis** [comment]
> I'm not blocking 0.9.6 just because of icons ;) I will just add identical padding in the SVGs and call them _2. Will refactor this for v1.

i would not even suggest that this are just improvements not critical  things

**Comment by rodlie** [comment]
![random-001](https://github.com/friction2d/friction-icon-theme/assets/34516798/bc36efbf-b9e7-4abc-93fd-a58562352d29)
![random-002](https://github.com/friction2d/friction-icon-theme/assets/34516798/29c8b441-106b-4846-9033-57c2a581251d)


Good enough™ *(will try to adjust the background fill rect size in the code, but that's not an icon issue)*

**Comment by adambelis** [comment]
We can iterate later :)
